namespace Server.Model.Entities
{
    public enum CandidateStatus
    {
        Active = 1,
        Inactive = 2,
        Hired = 3,
        Rejected = 4
    }

    public enum CandidateSource
    {
        Manual = 1,
        CVUpload = 2,
        ExcelImport = 3,
        LinkedIn = 4,
        Referral = 5
    }

    public class Candidate
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Address { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? Country { get; set; }
        public string? PostalCode { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string? CurrentPosition { get; set; }
        public string? CurrentCompany { get; set; }
        public decimal? CurrentSalary { get; set; }
        public decimal? ExpectedSalary { get; set; }
        public string? ExperienceSummary { get; set; }
        public string? Education { get; set; }
        public string? Certifications { get; set; }
        public string? Languages { get; set; }
        public string? Notes { get; set; }
        public string? LinkedInProfile { get; set; }
        public string? PortfolioUrl { get; set; }
        public CandidateStatus Status { get; set; } = CandidateStatus.Active;
        public CandidateSource Source { get; set; } = CandidateSource.Manual;
        public string? SourceDetails { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }
        public int CreatedByUserId { get; set; }
        public DateTime? LastContactDate { get; set; }
        public string? LastContactNotes { get; set; }
        public bool IsAvailable { get; set; } = true;
        public DateTime? AvailableFromDate { get; set; }
        public bool IsAutoGenerated { get; set; } = false;

        public User CreatedByUser { get; set; }
        public ICollection<CandidateSkill> CandidateSkills { get; set; } = new List<CandidateSkill>();
        public ICollection<CandidateCV> CandidateCVs { get; set; } = new List<CandidateCV>();
        public ICollection<CandidateJobMatch> CandidateJobMatches { get; set; } = new List<CandidateJobMatch>();
    }
}
