using Microsoft.AspNetCore.Http;

namespace Server.Model.DTO
{
    public class CandidateProfileDto
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string? PhoneNumber { get; set; }
        public string? CurrentPosition { get; set; }
        public string? CurrentCompany { get; set; }
        public string? ExperienceSummary { get; set; }
        public string? Education { get; set; }
        public List<string> Skills { get; set; } = new List<string>();
        public List<string> Certifications { get; set; } = new List<string>();
        public List<string> Languages { get; set; } = new List<string>();
        public int Source { get; set; }
        public string SourceName { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool IsAutoGenerated { get; set; }
    }

    public class CVProcessingResultDto
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public CandidateProfileDto? CandidateProfile { get; set; }
        public List<string> ExtractedSkills { get; set; } = new List<string>();
        public List<string> ExtractedCertifications { get; set; } = new List<string>();
        public string? ExtractedExperience { get; set; }
        public string? ExtractedEducation { get; set; }
        public string? RawContent { get; set; }
        public List<string> ProcessingErrors { get; set; } = new List<string>();
    }

    public class BulkImportResultDto
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public int TotalRows { get; set; }
        public int SuccessfulImports { get; set; }
        public int FailedImports { get; set; }
        public List<ImportErrorDto> Errors { get; set; } = new List<ImportErrorDto>();
        public List<CandidateDto> CreatedCandidates { get; set; } = new List<CandidateDto>();
    }

    public class ImportErrorDto
    {
        public int RowNumber { get; set; }
        public string FieldName { get; set; }
        public string ErrorMessage { get; set; }
        public string? RowData { get; set; }
    }

    public class ExcelImportDto
    {
        public IFormFile File { get; set; }
        public bool AutoCreateSkills { get; set; } = true;
        public bool SkipDuplicates { get; set; } = true;
        public string? SourceDetails { get; set; }
    }

    public class CandidateMatchDto
    {
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string CandidateEmail { get; set; }
        public decimal MatchScore { get; set; }
        public List<string> MatchingSkills { get; set; } = new List<string>();
        public List<string> MissingSkills { get; set; } = new List<string>();
        public string? Notes { get; set; }
    }

    public class JobMatchRequestDto
    {
        public int JobOpeningId { get; set; }
        public decimal MinMatchScore { get; set; } = 0.5m;
        public bool IncludeInactiveCandidates { get; set; } = false;
        public int? Limit { get; set; }
    }

    public class ProfileSearchDto
    {
        public string? SearchTerm { get; set; }
        public List<int> SkillIds { get; set; } = new List<int>();
        public List<int> SkillCategoryIds { get; set; } = new List<int>();
        public string? ExperienceLevel { get; set; }
        public string? Location { get; set; }
        public decimal? MinSalary { get; set; }
        public decimal? MaxSalary { get; set; }
        public bool IsAvailable { get; set; } = true;
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 20;
    }
}
